/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CactusModel(props) {
  const { nodes, materials } = useGLTF('./cactus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.002']}
        position={[0, 1.273, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.001']}
        position={[0, 4.758, 0]}
        scale={[0.604, 1.439, 0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.001']}
        position={[0, 5.385, 1.277]}
        rotation={[Math.PI / 6, 0, 0]}
        scale={[0.439, 0.673, 0.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Material.001']}
        position={[0, 6.278, -1.024]}
        rotation={[2.618, 0, Math.PI]}
        scale={[0.439, 0.379, 0.531]}
      />
    </group>
  )
}

useGLTF.preload('/cactus.glb')