/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RoseModel(props) {
  const { nodes, materials } = useGLTF('./rose.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.003']}
        position={[0.746, 6.243, 0.852]}
        rotation={[Math.PI / 9, 0, -0.29]}
        scale={[0.654, 0.719, 0.654]}
      />
      <group position={[0, 1.452, 0]} rotation={[-Math.PI, 0, 0]} scale={[1.75, 1.083, 1.75]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_2.geometry}
          material={materials['Material.006']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Material.004']}
        position={[0, 3.68, 0]}
        scale={[0.186, 1.528, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.004']}
        position={[-0.932, 5.234, 0.508]}
        rotation={[1.871, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.003']}
        position={[0.599, 5.763, 0.682]}
        rotation={[Math.PI / 9, 0, -0.29]}
        scale={[1.375, 1.09, 1.375]}
      />
    </group>
  )
}

useGLTF.preload('/rose.glb')

