/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SproutModel(props) {
  const { nodes, materials } = useGLTF('/sprout.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Material.007']}
        position={[0.365, 0, 0]}
        scale={1.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials['Material.008']}
        position={[-0.032, 2.429, 0]}
        scale={[0.25, 1.538, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['Material.008']}
        position={[-0.032, 4.522, 1.434]}
        rotation={[1.011, 0, 0]}
        scale={[0.139, 1.538, 0.502]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.008']}
        position={[-0.032, 4.546, -1.507]}
        rotation={[2.131, 0, Math.PI]}
        scale={[0.139, 1.538, 0.502]}
      />
    </group>
  )
}

useGLTF.preload('/sprout.gltf')